import '../styles/globals.css';
import { Nunito_Sans } from 'next/font/google';
import Image from 'next/image';

const Nunito = Nunito_Sans({
  subsets: ['latin'],
  weight: ['300', '600', '800']
})

export const metadata = {
  title: 'Countries info',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className={Nunito.className} lang="en">
      <body>
        <header>
          <div>
            <h2>Where in the world?</h2>
            <ul className='button_dark_mode'>
              <li>
                <Image src='/moon.svg' height={16} width={16} alt='icon' />
                <p>Dark Mode</p>
              </li>
            </ul>
          </div>

        </header>
        {children}
      </body>
    </html>
  )
}
